### ISSUE TITLE
Adicionar https ao site

### ISSUE THREAD

**Issue by teles** [seoanalytics/seoanalytics.github.io#3]
O @woliveiras havia comentado que ele tem uma forma gratuita de colocar https no blog.
Estou abrindo essa issue para discutirmos isso e ajudarmos na implementação do https.

cc @fabiolafaria

**Comment by fabiolafaria** [comment]
Comenta aí p gente colega @woliveiras :)

**Comment by woliveiras** [comment]
Tem esse carinha aqui:

https://www.cloudflare.com/

Tem de criar uma conta nele (free) e lá ele tem alguns serviços:

![screenshot from 2016-09-20 21 17 21](https://cloud.githubusercontent.com/assets/4243601/18693376/a9bf1b56-7f77-11e6-8241-299d13a03619.png)

Entre eles tem o HTTPS e Cache! \o/

**Comment by teles** [comment]
Conseguiu arrumar isso, @fabiolafaria ? A issue está fechada?

**Comment by fabiolafaria** [comment]
finalizado!
